name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json
    - run: dotnet build RDB
    - name: Create the package
      run: dotnet pack --configuration Release RDB
    - name: Publish the package to GPR
      run: dotnet nuget push RDB/bin/Release/*.nupkg --api-key ${{ env.GITHUB_API_KEY }} --skip-duplicate
